server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql//127.0.0.1:3306
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*./xml
  config-location: classpath:/mybatis/config/mybatis-config.xml